#!/bin/dash -e
# -*- sh -*-
if [ "$1" = -h ]
then
  cat /usr/local/share/awklib.txt
elif [ "$1" = -v ]
then
  cat /usr/local/share/stdlib.txt
elif [ "$1" = -f ]
then
  exec awk -f /usr/local/share/libstd.awk "$@"
else
  exec awk "$(cat /usr/local/share/libstd.awk)$@"
fi
