#!/bin/dash -e
# -*- sh -*-
if [ "$1" = -v ]
then
  cat /usr/local/share/stdlib.txt
elif [ "$1" = -f ]
then
  awk -f /usr/local/share/libstd.awk "$@"
else
  shift
  awk "$(cat /usr/local/share/libstd.awk)$@"
fi
