#!/bin/dash -e
# -*- sh -*-
if [ "$1" = -v ]
then
  cat /usr/local/share/stdlib.txt
elif [ "$1" = -c ]
then
  . /usr/local/share/libstd.sh
  z=$2
  shift 2
  eval "$z"
else
  shift
  z=$(cat "$1")
  dash -c ". /usr/local/share/libstd.sh; $z" "$@"
fi
