#!/bin/dash -e
# -*- sh -*-
case $1 in
-f)
  shift
  z=$(cat /usr/local/share/libstd.sh "$1")
  dash -c "$z" "$@"
;;
-c)
  shift
  . /usr/local/share/libstd.sh
  "$@"
;;
-v)
  cat /usr/local/share/stdlib.txt
esac
