#!/bin/dash -e
# -*- sh -*-
x=$# y=$1 z=$2
if [ "$x" -ge 2 ]
then shift 2
fi
if [ ! "$z" ]
then z=/dev/null
fi
case $y in
awk)
  awk -f /usr/share/awk/libstd.awk -f "$z" "$@"
;;
sh)
  . /usr/share/sh/libstd.sh
  . "$z" "$@"
;;
version)
  echo 1.0.0
esac
