#!/bin/dash -e
# -*- sh -*-
x=$1 y=$2
if [ "$#" -ge 2 ]
then shift 2
fi
if [ ! "$y" ]
then y=/dev/null
fi
case $x in
awk)
  awk -f /usr/local/share/libstd.awk -f "$y" "$@"
;;
sh)
  . /usr/local/share/libstd.sh
  . "$y" "$@"
;;
version)
  echo 1.2.1
esac
unset x y
